image: node

before_script:
  - npm install

variables:
  SURGE_DOMAIN: https://luxjoshyua-staging.surge.sh

build:
  stage: build
  before_script:
    - npm run ci
  script:
    - npm run build
  artifacts:
    paths:
      - build

deploy:
  stage: deploy
  before_script:
    - npm install -g surge
  script:
    - surge ./dist $SURGE_DOMAIN --token $SURGE_TOKEN
