# we just want to cache our package-lock and node_modules during the stages
cache:
  key:
    files:
      - package-lock.json
  paths:
    - node_modules/
# define stages
stages:
  - build
  - deploy
# define variables you can refer to them using "$" and the variable name
variables:
  SURGE_DOMAIN: https://luxjoshyua-staging-domain.surge.sh

# make sure you cache the build file since you might want to deploy the same changes over and over without running the pipeline
build:
  stage: build
  before_script:
    - npm run ci
  script:
    - npm run build
  artifacts:
    paths:
      - build
deploy:
  stage: deploy
  before_script:
    - npm install -g surge
  script:
    - surge ./dist $SURGE_DOMAIN --token $SURGE_TOKEN
