image: node

before_script:
  - npm install

variables:
  SURGE_DOMAIN: https://luxjoshyua-staging.surge.sh
  SURGE_TOKEN: 6822396678785becc1700323e270c605

deploy:
  stage: deploy
  before_script:
    - npm install -g surge
  script:
    - surge ./dist $SURGE_DOMAIN --token $SURGE_TOKEN .
